#!/bin/sh

if [ -f /etc/os-release ] || [ -f /usr/lib/os-release ];then
	. /etc/os-release
	echo -e "Welcome to $PRETTY_NAME!"	
fi

# mount fstab
mkdir -p /dev/pts
mkdir -p /dev/i2c
/bin/mount -a

echo -e "\t\tSetting up mdev ..."
echo /sbin/mdev > /proc/sys/kernel/hotplug
/sbin/mdev -s
mount -t devpts devpts /dev/pts

echo -e "\t\tSet up HOSTNAME ..."
if [ -f /etc/hostname ]; then
    /bin/hostname -F /etc/hostname
else
    HOSTNAME=localhost
    /bin/hostname $HOSTNAME
fi

echo -e "\t\tLoading Net Drivers ..."
modprobe stmmac
modprobe stmmac_platform
modprobe dwmac_stm32
modprobe r8152

echo -e "\t\tStarting networking ..."
/etc/init.d/networking start

echo -e "\t\tStarting Dropbear SSH server..."
if [ -f /var/run/ifstate ];then
	echo > /var/run/ifstate
fi

/etc/init.d/dropbear start
