#!/bin/sh

if [ -f /etc/os-release ] || [ -f /usr/lib/os-release ];then
	. /etc/os-release
	echo -e "Welcome to $PRETTY_NAME!"	
fi

# mount fstab
mkdir -p /dev/pts
mkdir -p /dev/i2c

/bin/mount -a

#echo "Setting wathcdog"
#watchdog -t 30 /dev/watchdog0

echo "         Setting up mdev ..."
echo /sbin/mdev > /proc/sys/kernel/hotplug
/sbin/mdev -s
mount -t devpts devpts /dev/pts

echo -e "         Set up HOSTNAME ..."
if [ -f /etc/hostname ]; then
    /bin/hostname -F /etc/hostname
else
    HOSTNAME=localhost
    /bin/hostname $HOSTNAME
fi

echo "         Loading Net Drivers ..."
modprobe stmmac
modprobe stmmac_platform
modprobe dwmac_stm32
modprobe r8152

echo "         Starting networking ..."
#/sbin/ifconfig lo 127.0.0.1
/etc/init.d/networking start
#/etc/rc.d/init.d/netd start
#/sbin/udhcpc -i eth0
#/etc/init.d/ifconfig-eth0
